### ISSUE TITLE
Skrivefeil i catalog-of-models-for-spesifications.ttl

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/model-publisher#48]
Endre tittel på fil som følger:
> spesifications -> specifications

Endre innhold som følger:

Linje 18: 
> forvaltningsstander -> forvaltningsstandarder

Mange stader: 
> spesifications -> specifications

**Comment by jimjyang** [comment]
Takk, @stigbd. Rettes opp nå.
