### ISSUE TITLE
Slette de gamle modellene fra FDK

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/model-publisher#49]
@stigbd

Ved å rette opp en av de skrivefeilene du påpekte, issue #48, ble IRIen til modellene endret, og dette førte til at modellene finnes nå dobbelt opp i FDK, som jeg ikke tenkte på før jeg lastet modellene til FDK :-(. 

Kan du hjelpe med å slette de gamle, dvs. de med "spesifications" i IRIen?

**Comment by stigbd** [comment]
Sender den vidare til ETL-divisjonen.

**Comment by valosnah** [comment]
Den gamle versjonen er nå ikke lenger søkbar i FDK.

**Comment by stigbd** [comment]
@jimjyang Viss denne løsninga er tilstrekkelig, kan du lukke saken.

**Comment by jimjyang** [comment]
Takk, det er tilstrekkelig!
